---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxygen-hw7-pvc
  labels:
    username: "oxygen"
    env: "test"
spec:
  storageClassName: "rbd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi