---
apiVersion: v1
kind: Service
metadata:
  name: oxygen-hw7-redis-service
spec:
  type: ClusterIP
  selector:
    username: "oxygen"
    env: "test"
  ports:
  - name: oxygen-hw7-redis-service
    port: 6379
    targetPort: 6379