---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-test-flask-deployment
  labels:
    username: "oxygen"
    env: "test"
    app: "flask"
spec:
  replicas: 2
  selector:
    matchLabels:
      username: "oxygen"
      env: "test"
      app: "flask"
  template:
    metadata:
      labels:
        username: "oxygen"
        env: "test"
        app: "flask"
    spec:
      containers:
        - name: oxygen-test-flask-container
          imagePullPolicy: Always
          image: agentoxygen/flask:1.0
          env:
            - name: FLASK_APP
              value: "/data/app.py"
            - name: REDIS_IP
              value: "10.103.127.200"
          ports:
          - name: http
            containerPort: 5000