---
apiVersion: v1
kind: Service
metadata:
  name: oxygen-hw7-flask-service
spec:
  type: ClusterIP
  selector:
    username: "oxygen"
    env: "test"
    app: "flask-hw7"
  ports:
  - name: oxygen-hw7-flask-service
    port: 5000
    targetPort: 5000